apiVersion: v1
kind: Pod
metadata:
  name: active-mq
  labels:
    app: active-mq
spec:
  volumes:
    - name: active-mq-storage
      persistentVolumeClaim:
        claimName: active-mq-pvc

  containers:
    - name: active-mq
      image: dewab/lab-activq-mq
      imagePullPolicy: Always
      ports:
        - containerPort: 8161
          name: dashboard
        - containerPort: 61616
          name: openwire
        - containerPort: 5672
          name: amqp
        - containerPort: 61613
          name: stomp
        - containerPort: 1883
          name: mqtt
      volumeMounts:
        - name: active-mq-storage
          mountPath: /home/alpine/apache-activemq-5.18.3/conf/jetty-realm.properties
          subPath: jetty-realm.properties
      resources:
        requests:
            memory: 500Mi
            cpu: 200m
        limits:
            memory: 1000Mi
            cpu: 400m
